apiVersion: v1
kind: ConfigMap
metadata:
  name: log-config
  namespace: appd
data:
  log4j.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <configuration status="Warn" monitorInterval="30">

        <Appenders>
            <Console name="ConsoleAppender" target="SYSTEM_OUT">
                <PatternLayout pattern="%d{ABSOLUTE} %5p [%t] %c{1} - %m%n"/>
            </Console>
        </Appenders>

        <Loggers>
            <Logger name="com.singularity" level="info" additivity="false">
                <AppenderRef ref="ConsoleAppender"/>
            </Logger>
            <Logger name="com.appdynamics" level="info" additivity="false">
                <AppenderRef ref="ConsoleAppender"/>
            </Logger>
            <Logger name="com.singularity.ee.agent.systemagent.task.sigar.SigarAppAgentMonitor" level="info" additivity="false">
                <AppenderRef ref="ConsoleAppender"/>
            </Logger>
            <Root level="error">
                <AppenderRef ref="ConsoleAppender"/>
            </Root>
        </Loggers>

    </configuration>
