apiVersion: v1
kind: ConfigMap
metadata:
  name: appd-db-agent-properties
  namespace: appd  
data:
#  ----- comment out properties whichever required -----
  APPDYNAMICS_CONTROLLER_HOST_NAME: ""
  APPDYNAMICS_CONTROLLER_PORT: "443"
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: "true"
  APPDYNAMICS_DB_AGENT_NAME: ""
  APPDYNAMICS_AGENT_ACCOUNT_NAME: ""

  APPDYNAMICS_DB_PROPERTIES: "-Ddisable.kubernetes.host.resolver=true"
  APPDYNAMICS_AGENT_UNIQUE_HOST_ID: ""
  
